#include "mainwindow.h"
#include "ui_mainwindow.h"
#include <QPrinter>
#include <QPainter>
#include <QFileDialog>
#include <QMessageBox>
#include <QTextDocument>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    connect(ui->doublespin_mzda, &QDoubleSpinBox::valueChanged, this, &MainWindow::vypocetMzdy);

    connect(ui->pushButton_exportPDF, &QPushButton::clicked, this, &MainWindow::exportPDF);
}

MainWindow::~MainWindow()
{
    delete ui;
}

QString MainWindow::formatMoney(double value)
{
    return QLocale(QLocale::Czech).toString(value, 'f', 2) + " CZK";
}
void MainWindow::vypocetMzdy()
{
    double Dan = ui->doublespin_mzda->value() * 0.15;
    ui->label_danV->setText(QString::number(Dan) + " CZK");

    double Socialni = ui->doublespin_mzda->value() * 0.071;
    ui->label_socV->setText(QString::number(Socialni) + " CZK");

    double Zdravotni = ui->doublespin_mzda->value() * 0.045;
    ui->label_zdraV->setText(QString::number(Zdravotni) + " CZK");

    double result = ui->doublespin_mzda->value() - Dan - Socialni - Zdravotni;
    ui->label_vysledek->setText(QString::number(result) + " CZK");
}

void MainWindow::exportPDF()
{
    QString fileName = QFileDialog::getSaveFileName(
        this,
        "Export Wage Calculation",
        "wage-calculation.pdf",
        "PDF Files (*.pdf)"
        );

    if (fileName.isEmpty())
        return;

    QPrinter printer(QPrinter::HighResolution);
    printer.setOutputFormat(QPrinter::PdfFormat);
    printer.setPageSize(QPageSize(QPageSize::A4));
    printer.setPageMargins(QMarginsF(20, 20, 20, 20));
    printer.setOutputFileName(fileName);

    QTextDocument document;

    QString grossWage =
        QString::number(ui->doublespin_mzda->value(), 'f', 2) + " CZK";

    QString social = ui->label_socV->text();
    QString health = ui->label_zdraV->text();
    QString tax = ui->label_danV->text();
    QString netWage = ui->label_vysledek->text();

    QString html = QString(R"(
<html>
<head>
<style>

body {
    font-family: Arial;
    font-size: 18pt;
    color: #222222;
}

.title {
    text-align: center;
    font-size: 32pt;
    font-weight: bold;
    margin-bottom: 8px;
}

.subtitle {
    text-align: center;
    font-size: 16pt;
    color: #666666;
    margin-bottom: 35px;
}

.section {
    font-size: 22pt;
    font-weight: bold;
    margin-bottom: 18px;
}

table {
    width: 100%;
}

td {
    font-size: 18pt;
    padding: 16px;
}

.label {
    font-weight: normal;
}

.amount {
    text-align: right;
    font-weight: bold;
}

.net {
    font-size: 25pt;
    font-weight: bold;
    padding: 22px;
}

.footer {
    text-align: center;
    font-size: 12pt;
    color: #777777;
}

</style>
</head>

<body>

<div class="title">
Wage Calculator
</div>

<div class="subtitle">
Wage calculation report
</div>

<div class="section">
Wage overview
</div>

<table>

<tr>
<td class="label">
Gross wage
</td>
<td class="amount">
%1
</td>
</tr>

<tr>
<td class="label">
Social insurance
</td>
<td class="amount">
%2
</td>
</tr>

<tr>
<td class="label">
Health insurance
</td>
<td class="amount">
%3
</td>
</tr>

<tr>
<td class="label">
Income tax
</td>
<td class="amount">
%4
</td>
</tr>

</table>

<br><br>

<table>

<tr>
<td class="net">
Net wage
</td>

<td class="net amount">
%5
</td>
</tr>

</table>

<br><br><br>

<div class="footer">
Generated by Wage Calculator<br><br>
Copyright © 2026 Josef Štěpánek
</div>

</body>
</html>
)")
                       .arg(grossWage)
                       .arg(social)
                       .arg(health)
                       .arg(tax)
                       .arg(netWage);

    document.setHtml(html);

    document.print(&printer);

    QMessageBox::information(
        this,
        "PDF Export",
        "The wage calculation has been successfully exported."
        );
}